### ISSUE TITLE
Sidebar Menu

### ISSUE THREAD

**Issue by rmclain** [yadahan/nova-bouncer#1]
I've installed bouncer and then followed the instructions to install Nova-Bouncer, but still, I am not seeing it show up in the sidebar. Is there something I'm missing from the install process?

**Comment by yakidahan** [comment]
Only for users who are authorized to manage the Bouncer models, the navigation menu is displayed.

You may give ability to manage the Bouncer models for a user\role in this way:

```php
$user = User::find(1);

Bouncer::allow($user)->toManage(\Silber\Bouncer\Database\Role::class);
Bouncer::allow($user)->toManage(\Silber\Bouncer\Database\Ability::class);

// or

Bouncer::role()->create([
    'name' => 'manage-bouncer',
    'title' => 'Manage bouncer',
]);

Bouncer::allow('manage-bouncer')->toManage(\Silber\Bouncer\Database\Role::class);
Bouncer::allow('manage-bouncer')->toManage(\Silber\Bouncer\Database\Ability::class);

$user->assign('manage-bouncer');
```

The package is still in development so documentation is not complete yet...

**Comment by yakidahan** [comment]
I have updated the documentation, see the [Basic Usage](https://github.com/yadahan/nova-bouncer#basic-usage) section.

**Comment by rmclain** [comment]
I'm still getting an issue assigning a user to the role using the example you provided. 

`Non-static method Silber\Bouncer\Bouncer::role() should not be called statically`

Update: nvm figured it out. Was using the wrong namespace.  Updated to use Silber\Bouncer\BouncerFacade as Bouncer; and works fine. Thanks.

**Comment by yakidahan** [comment]
All examples in the docs use the facade.

Try to add this:

```php
use Silber\Bouncer\BouncerFacade as Bouncer;
```
