### ISSUE TITLE
Support Custom Role & Ability Models

### ISSUE THREAD

**Issue by calvinps** [yadahan/nova-bouncer#10]
Bouncer has support for extending the base Role and Ability classes, but it seems that the relationships of extended bouncer classes don't load properly.

Specifically, I am using an extended Role class and when I go to the index page for my role I don't see any of the abilities. I found that if I chance the `public static $model = 'Silber\Bouncer\Database\Role'` to `public static $model = 'App\Models\Role'` (my custom role class) in `Yadahan\BouncerTool\Nova\Role` then the role's abilities will show up. 

Maybe you could update it so that custom role/ability classes can be defined in `config/bouncer-tool.php` and used as the  `public static $model` in `Yadahan\BouncerTool\Nova\Role` and `Yadahan\BouncerTool\Nova\Ability`?

If it helps, the reason the abilities don't load in my case is because the mysql query includes the WHERE clause `permissions.entity_type = 'Silber\Bouncer\Database\Role'`, but none of my permissions match that entity_type since I'm using a different model.

**Comment by ghost** [comment]
@calvinps with #11, there's not even a need to configure the models

**Comment by yakidahan** [comment]
I added support for custom Role & Ability in the new release [v0.2.0](https://github.com/yadahan/nova-bouncer/releases/tag/v0.2.0).
