### ISSUE TITLE
Can not install with silber/bouncer v1.0.0-rc.8 

### ISSUE THREAD

**Issue by tititorn** [yadahan/nova-bouncer#15]
Using version ^0.4.0 for yadahan/nova-bouncer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yadahan/nova-bouncer ^0.4.0 -> satisfiable by yadahan/nova-bouncer[v0.4.0].
    - yadahan/nova-bouncer v0.4.0 requires silber/bouncer v1.0.0-rc.4|v1.0.0-rc.5|v1.0.0-rc.6|v1.0.0-rc.7 -> satisfiable by silber/bouncer[v1.0.0-rc.4, v1.0.0-rc.5, v1.0.0-rc.6, v1.0.0-rc.7] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by yakidahan** [comment]
I added support for silber/bouncer v1.0.0-rc.8 in the new release [v0.5.0](https://github.com/yadahan/nova-bouncer/releases/tag/v0.5.0).
