### ISSUE TITLE
Refresh cache

### ISSUE THREAD

**Issue by fibis** [yadahan/nova-bouncer#18]
We have the Bouncer cache permanently active. So, after we made changes to roles, abilities and permissions, we need to refresh the cache. 

Is there a possibility that the cache is automatically refreshed, when we change one of the above?

**Comment by yakidahan** [comment]
Hi @fibis ,

I think that's a question for the [Bouncer](https://github.com/JosephSilber/bouncer) package,
This package is just an interface for the [Bouncer](https://github.com/JosephSilber/bouncer) package.
