### ISSUE TITLE
Only owner

### ISSUE THREAD

**Issue by Krato** [yadahan/nova-bouncer#2]
Hello, thanks for your tool! 😄 

How can I create an Ability to edit/view just your own user? I'm unable to get it.

Thanks!

**Comment by yakidahan** [comment]
Hi,

By default, Bouncer will check the model's `user_id` against the current user's primary key.

To create an ability to your own user it's little bit tricky, you need to set up the User model ownership attribute to `id` instead `user_id`.

According the Bouncer [Ownership](https://github.com/JosephSilber/bouncer#ownership) documentation, you can do it by this way:

```php
// in app/Providers/AppServiceProvider

use App\User;
use Silber\Bouncer\BouncerFacade as Bouncer;

public function boot()
{
    // ...
    Bouncer::ownedVia(User::class, 'id');
}
```

Now you can create any ability to your own user, Here's an example of what that might look like:

![screenshot from 2018-10-11 05-33-53](https://user-images.githubusercontent.com/7757560/46778572-f64fbf80-cd1c-11e8-8b99-2eb942c95ee4.png)

Good luck!
