### ISSUE TITLE
Nova 4 Support

### ISSUE THREAD

**Issue by remxcode** [yadahan/nova-bouncer#21]
Thanks for your work!

**Comment by yakidahan** [comment]
Hi @remxcode,
I'm on it...

**Comment by mbaxter91288** [comment]
hi @yakidahan thanks for your work. Just wondering if you had a rough ETA on this? I have a project I'd like to upgrade to Nova 4 and just trying to schedule the time :)

Not pushing just wondering :)

**Comment by yakidahan** [comment]
Hi,

Thank you for using this package.

I added Nova 4 support (and some cool features) in the new release [v2.0.0](https://github.com/yadahan/nova-bouncer/releases/tag/v2.0.0).

**Comment by mbaxter91288** [comment]
Amazing thanks!
