### ISSUE TITLE
Target class [translator] doesn't exist after publishing config

### ISSUE THREAD

**Issue by simonhamp** [yadahan/nova-bouncer#23]
It seems the timing of the config being loaded when it's in the application's config directory is too early to use the `__()` function.

You should probably move the translation work out to your other classes, closer to where and when it's needed, rather than have it happen inside the config file itself.

**Comment by yakidahan** [comment]
Hi @simonhamp,

Thanks for reporting.

This issue was fixed in the new release [v2.0.1](https://github.com/yadahan/nova-bouncer/releases/tag/v2.0.1).
