### ISSUE TITLE
Forbidden and Scope in attach not updating

### ISSUE THREAD

**Issue by Krato** [yadahan/nova-bouncer#3]
After attach an ability to a role I'm able to set the Forbidden check and Scope field. But once saved the resource is giving always a Forbidden in red.

Also when I want to update Forbidden is always unchecked and also scope.

Thanks!

**Comment by yakidahan** [comment]
Since the Bouncer does not load the pivot attributes, these attributes fields will not be defined.

I submitted a [pull request](https://github.com/JosephSilber/bouncer/pull/356) to fix this issue.

**Comment by yakidahan** [comment]
The [PR](https://github.com/JosephSilber/bouncer/pull/356) was merged (https://github.com/JosephSilber/bouncer/commit/aee68cf9e74698f44e7afd39da67883ae17a9301).

Update `silber/bouncer` to `dev-master` to resolve this issue:

    composer require silber/bouncer dev-master
