### ISSUE TITLE
Forbid everything but edit one

### ISSUE THREAD

**Issue by Krato** [yadahan/nova-bouncer#4]
Hello, first sorry. But I don't understand how it works at all.

How can forbid a model, but let the user to edit a model id? I tried creating two abilities. One to forbid evertything in the model, and another ability to edit a model id. But not working, is always forbidden.

Thanks

**Comment by yakidahan** [comment]
Hi @Krato,

I didn't really understand what you were trying to do, but I think that's a question for the [Bouncer](https://github.com/JosephSilber/bouncer) package.

This package is just an interface for the [Bouncer](https://github.com/JosephSilber/bouncer) package.
