### ISSUE TITLE
Ability to show/hide sections

### ISSUE THREAD

**Issue by johan-steffens** [yadahan/nova-bouncer#8]
Thanks for the great package.

I was wondering whether there's a way to show/hide sidebar sections generated by Tools based on roles or abilities?

As an example, I use [Nova Log Viewer](https://novapackages.com/packages/php-junior/nova-logs) on a CMS and only want users with the System Administrator role be able to manage logs.

**Comment by yakidahan** [comment]
of course!

Look at the documentation in the [Basic Usage](https://github.com/yadahan/nova-bouncer#basic-usage) section:

> Only users who are authorized to manage the Bouncer models can see this navigation items.

**Comment by johan-steffens** [comment]
@yakidahan this works fine for the Bouncer tab, but I'm not sure how to show/hide another Tool's management section, as an example the *Log Viewer* section in the image below.

![Log Viewer](https://i.imgur.com/ScoIjN9.png)
